### PR TITLE
Added support to delay between commands when running a macro

### PR DESCRIPTION
**Pull request by rotolonico**
When a new macro is created, the macro command has a parameter which is the delay; this value represents the value in seconds of delay time between the execution of each command in the macro.

This might be useful for macros that contain asynchronous commands or commands that require the end of the frame to be completed (for example, a macro composed of two commands, the first one spawns an object, the second one finds that object by its name and changes its color. These two commands can't occur in the same frame so a simple macro without a delay would not work).

In addition to that, if the delay is set to zero, the commands in the macro will be executed one every frame. Finally, if the delay is less than zero, the macro will run normally.

Coding-wise, I have added a MacroPlayerHelper.cs Monobehaviour class (Monobehaviour is needed to support coroutines), which will handle the playing of the macro. This script will be automatically attached to the same object that has the ConsoleView.cs attached; this way it will never get destroyed.

### CODE REVIEW

**Comment by LukaszKr** [comment]
I see what you are trying to do here. But it will not work for chained commands as you can also do:
`commandA; commandB; commandC` 
Or with -repeat option.
I think what would be better is to have command itself have a way of saying that it's an async. And as it's already doing reflection I could probably turn method in commands to support yield.

**Comment by LukaszKr** [comment]
Also then delay could be added as an option. So you could write:
`commandA -repeat 5 -delay 5000` 
To have it execute 5 times with 5 second delays.

**Comment by LukaszKr** [comment]
I've changed execution logic so that Commands can return Message as before, and IEnumerator when they will be treated as Coroutines. Also there is now "-delay sec" option for every command by default. If multiple async commands are issues, they will be queued.

Example of command using it:
https://github.com/LukaszKr/PowerConsole/blob/master/PowerConsole/Assets/Plugins/ProceduralLevel/PowerConsole/Example/Code/AsyncPrintCommand.cs

Commit:
 https://github.com/LukaszKr/PowerConsole/commit/c5efa5c11e3d33ec6dd95309ecf3dc8138297419 

I think this is the functionality that you wanted for macros, but extended so that it covers all use cases. If it's not, please let me know and we will see about this merge.

**Comment by rotolonico** [comment]
Yes, Async commands sound like a better and more extended solution; this also covers my use case so it should be exactly what I needed; thanks!

**Pull request closed without merging**
